version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "80:5173"
    environment:
      - SERVER_URL=http://localhost:5000

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SHORTCUT_URL_DOMAIN=http://localhost:5000
      - SecretKey="shuuuu...."
      - MYSQL_HOST="your-host"
      - MYSQL_USER=="user"
      - MYSQL_PASSWORD="your-password"
      - MYSQL_DATABASE_NAME="databasename"
  
