version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "80:80"
    environment:
      PORT: 80
      VITE_Server_URL: "http://localhost:5000"

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      SHORTCUT_URL_DOMAIN: "http://localhost:5000"
      SecretKey: "shuuuu...."
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "my-pass"
      MYSQL_DATABASE_NAME: "short_url"

    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "my-pass"
      MARIADB_DATABASE: "short_url"